cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
   name: mongodb-secret
type: opaque
data:
  MONGO-ROOT-USERNAME: dXNlcm5hbWU=
  MONGO-ROOT-PASSWORD: cGFzc3dvcmQ=
  
  Note: You need to deploy the secret file first for deployment to be build.
EOF
